<?php

namespace AppBundle\Repository;

/**
 * AccesTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccesTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
