services:
    serializer_listener.produces:
        class: AppBundle\Serializer\Listener\ProducesListener
        tags:
            - { name: jms_serializer.event_subscriber }
            
    app.exception_subscriber:
        class: AppBundle\EventSubscriber\ExceptionListener
        arguments: ['@jms_serializer']
        tags:
            - { name: kernel.event_subscriber }

    app.normalizer.resource_validation_exception:
        class: AppBundle\Normalizer\NotFoundHttpExceptionNormalizer
        arguments:
            - { type: 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'  }
        tags:
            - { name: app.normalizer }
    
    facebook_authenticator:
        class: AppBundle\Security\FacebookAuthenticator
    
    facebook_user_provider:
        class: AppBundle\Security\FacebookUserProvider
        arguments: ["@csa_guzzle.client.facebook_api", "@jms_serializer", "@doctrine.orm.default_entity_manager"]
