fos_oauth_user_security_login:
    path: /auth/login
    defaults: { _controller: FOSUserBundle:Security:login }
 
fos_oauth_user_security_check:
    path: /auth/check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST
 
fos_oauth_user_security_logout:
    path: /auth/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

